### ISSUE TITLE
大佬考虑写一下how to run&use吗

### ISSUE THREAD

**Issue by HuChuYangALICE** [qian-o/SabaSharp#4]
这里的环境是linux

**Comment by qian-o** [comment]
你需要确认系统为x64环境并且支持gles3.2才可以，因为该项目基于.NET，只需要安装对应.NET版本sdk就好。

**Comment by qian-o** [comment]
https://learn.microsoft.com/zh-cn/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website

这个是安装环境的教程，使用 dotnet xxx.dll 运行程序。
虚拟机好像只支持到opengl es 3.0，不过你将程序的gl版本改成3.0应该也可以运行。
