### ISSUE TITLE
不错的工程，请问是否有将其移植到unity的打算？

### ISSUE THREAD

**Issue by Liufour** [qian-o/SabaSharp#6]
我还没有查看你的项目，我是在网上研究pmx模型文件的格式发现的saba，进而发现了你的项目，并发现整个项目已经被移植到c#了。我曾在unity中编写了可以直接读取相机动作文件的脚本优化了mmd到unity的工作流。我一直都有一个想法，让unity可以实现像原生mmd软件一样可以靠鼠标拖拽模型、动作文件就可以完成一个完整视频的输出。我想知道你开发这个项目是否有这方向开发的打算？

**Comment by qian-o** [comment]
抱歉，我不会 Unity。
不过引擎中应该会有很多mmd导入的插件吧。
