### ISSUE TITLE
运行Saba库报错

### ISSUE THREAD

**Issue by superowner** [qian-o/SabaSharp#7]
TryCreateSvmArray这个函数疯狂报错，用new FixedArray<T>替换后也出现其他内存保护相关报错

**Comment by qian-o** [comment]
能发几张抛错的截图吗？

**Comment by superowner** [comment]
> 能发几张抛错的截图吗？

但凡遇到SVM buffer都会有问题，我的是英特尔GPU ，CPU也是英特尔的
![error](https://github.com/qian-o/SabaSharp/assets/15080614/a17f8602-629a-4b48-ac7d-fa3c453dfd9c)
TryCreateSvmArray初始化长度都是对的，但是一旦索引里面元素就报空指针

**Comment by qian-o** [comment]
这一般是ocl里svm内存创建失败了，你可以先改下创建那个函数，禁用掉cl的创建流程。 我明天会在看看这个问题。

**Comment by qian-o** [comment]
![Screenshot_2024-05-22-22-30-38-84_df198e732186825c8df26e3c5a10d7cd](https://github.com/qian-o/SabaSharp/assets/84434846/76bb9422-d726-40b9-af8e-48a2ebced0e3)

就这一段内容，如果您有时间的话，也可以帮我看看这个为什么会创建失败。🥳

**Comment by qian-o** [comment]
> > 能发几张抛错的截图吗？
> 
> 但凡遇到SVM buffer都会有问题，我的是英特尔GPU ，CPU也是英特尔的 ![错误](https://private-user-images.githubusercontent.com/15080614/332833575-a17f8602-629a-4b48-ac7d-fa3c453dfd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Mjk5NDEsIm5iZiI6MTcxNjQyOTY0MSwicGF0aCI6Ii8xNTA4MDYxNC8zMzI4MzM1NzUtYTE3Zjg2MDItNjI5YS00YjQ4LWFjN2QtZmEzYzQ1M2RmZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAyMDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMTA4NTgxMmVlNjQ5ZmZlZTExNTM4ZmIxN2E1NGRkODBlNTU4NDYwNTMwNGZhNWNmZDM2N2JjMjQ0ZjI5YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IrcLvYgaxGaNoEaRNZjIWeEeHK_cM8_4TiXbGsBaOjs) TryCreateSvmArray初始化长度都是对的，但是一旦索引里面元素就报空指针

更新下代码再尝试下。

> > 能发几张抛错的截图吗？
> 
> 但凡遇到SVM buffer都会有问题，我的是英特尔GPU ，CPU也是英特尔的 ![error](https://private-user-images.githubusercontent.com/15080614/332833575-a17f8602-629a-4b48-ac7d-fa3c453dfd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzA4NDEsIm5iZiI6MTcxNjQzMDU0MSwicGF0aCI6Ii8xNTA4MDYxNC8zMzI4MzM1NzUtYTE3Zjg2MDItNjI5YS00YjQ4LWFjN2QtZmEzYzQ1M2RmZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAyMTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZGFlMjM4Y2ExZGVmZTYyMTAwYWM4NmZmNjI2YWYxYmQ4YmMzNTcyNWJmMGVhYmJiYmJkYTNlNWRjMjI4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sv0Ay5AifQCPciTKiNibULT3Rpwo-KPC3VAtEWeasW4) TryCreateSvmArray初始化长度都是对的，但是一旦索引里面元素就报空指针

可以拉下代码再试试，我这边没有设备能复现你这个问题，只能猜测改了下。

**Comment by qian-o** [comment]
更新下代码再试试吧，我这边没有设备能复现您这个问题，只能猜测改了下。

**Comment by superowner** [comment]
> 更新下代码再试试吧，我这边没有设备能复现您这个问题，只能猜测改了下。

非常感谢，不过还是有问题，现在是界面打开都是正常，就是点play后也无法播放动画，退出后会报错
![dcsdfsdfsdfsdfsdfsd](https://github.com/qian-o/SabaSharp/assets/15080614/7dcbdf5e-6dec-413e-b177-3fd066563e6c)

**Comment by qian-o** [comment]
好吧，那我真不清楚问题出在哪里了。

**Comment by superowner** [comment]
> 好吧，那我真不清楚问题出在哪里了。

噢噢，能不能整个开关，另外一条分支是不用OpenCL的，估计问题就出在那里，具体说不清楚，估计是我的显卡不支持，我的是I卡750，我试了N卡的都没什么问题，A卡的不清楚

**Comment by qian-o** [comment]
> > 好吧，那我真不清楚问题出在哪里了。
> 
> 噢噢，能不能整个开关，另外一条分支是不用OpenCL的，估计问题就出在那里，具体说不清楚，估计是我的显卡不支持，我的是I卡750，我试了N卡的都没什么问题，A卡的不清楚

可以再拉取下代码试试。

![image](https://github.com/qian-o/SabaSharp/assets/84434846/a65aea19-73d0-4035-9d04-ebfc3d1706fb)

**Comment by qian-o** [comment]
这个 issue 就先关了，如果后续还有什么问题可以重新激活。
